### ISSUE TITLE
[Erweiterung] Social-Media-Bar

### ISSUE THREAD

**Issue by LBeckX** [1601com/social-media-bar#1]
### Timing:

- Deadline: 05.06.
- Zeitvorgabe: 16 Stunden

---

**Anforderungen**

* [x] Contao Erweiterung
* [x] Die Erweiterung kann über Pack a Gist installiert werden (Composer) - #5 
* [x] sm Erweiterung:
  - [x] Die smBar soll als extra Punkt in Seiten Navigation von Contao zu sehen sein, z.B. unter Inhaltselemente.
  - [x] Unter dem Punkt können beliebig viele smBars erstellt werden.
  - [x] Bei der Konfiguration der einzelnen smBars soll es folgende Einstellungsmöglichkeiten geben:
    - [x] Erstellen von beliebig vielen social media Feldern mit Auswahlmöglichkeit eines sm Icons, einfügen eines Teilen Links und eines Links zur sm Seite.
    - [x] Checkbox zum hinzufügen eines Ansprechpartners - Lösung über Mitglieder siehe unten
  - [x] Erstellte smBars sollen über die Module auswählbar und erstellbar sein
  - [x] Das Modul kann dann im Seitenlayout eingebunden werden.
* [x] Nötige Anpassungen Mitglieder:
  - [x] Es muss eine Auswahlmöglichkeit der Seiten, auf denen das entsprechende Mitglied ausgegeben werden soll, vorhanden sein - Auswahl von einzelnen Seiten oder z.B. gesamtem Seitenbaum
  - [x] Es muss möglich sein ein Bild und eventuell noch eine Beschreibung zu dem entsprechenden Mitglied zu ergänzen.

---

**Finalisierung**
- [x] Testen der Erweiterung in Contao 4.9 // 1 Stunde
- [x] Review mit LB // 0.5 Stunden
- [x] Kleine Anpassung: Auswahl der SM-Bar im Modul unter anderem Reiter (wie bei News)
- [x] [Veröffentlichung auf PackAGist](https://github.com/1601com/social-media-bar/issues/5) // 1 Stunde
- [x] Verbauen in dem Agentur-CMS // 1 Stunde
- [x] Done und Close

---

Altes Ticket: https://github.com/1601com/Agentur-CMS/issues/76

**Comment by vm1601com** [comment]
Die Erweiterung ist veröffentlich und im Agentur-cms verbaut. Habe diese in allen Layouts verbaut und noch einmal getestet.

Entwicklung ist abgeschlossen und hier kann zu.
