### ISSUE TITLE
PHP 8-Kompatibilität

### ISSUE THREAD

**Issue by avoca77** [1601com/social-media-bar#10]
Ist es geplant, die PHP 8 Kompatibilität herzustellen?
Läuft leider nicht unter PHP 8.1 mit Contao 4.9.38.
Danke!

**Comment by LBeckX** [comment]
Sorry, die Erweiterung wird leider nicht mehr weiterentwickelt.
Gerne kann aber ein Clone vom Repo erstellt werden und das weiterentwickelt werden.
