### ISSUE TITLE
Auswahl zwischen hellen und dunklen Icons

### ISSUE THREAD

**Issue by vm1601com** [1601com/social-media-bar#7]
## Beschreibung / User Stories
Um die Social Media Bar noch weiter zu vereinfachen und leichte Anpassungen zur Verfügung zu stellen, wäre es sinnvoll wenn zwischen dunklen und hellen social media Icons gewählt werden kann um diese je nach Hintergrund der Seite auszuwählen.

@LBeckX wie sinnvoll ist diese Anpassung deiner Meinung nach?

## Aufgaben, Akzeptanzkriterien & Aufwandseinschätzung
* [x] Implementierung von Theme switcher // **Aufwand: 3 Stunden**
  * [x] dunkle Icons müssen mit verbaut werden
  * [x] CSS muss überarbeitet werden
  * [x] Feld im Backend ergänzt werden
  * [x] Theme Klassenvergabe in Template integriert werden

## Ressourcen & Projektinformationen
* **Projektleitung:** 
* **Q-Aufgabe:** 
* **Stundenfreigabe:** 3 h
* **Deadline:** TT.MM.JJJJ

## Status
* [x] Briefing (Vorbesprechung) *(PL -> MA)*
* [x] Aufwandseinschätzung abgegeben *(MA -> PL)*
* [x] Angeboten *(PL)*
* [x] Beauftragt *(PL)*
* [x] Projektiert / Aufgabe angelegt *(PL)*
* [x] Ready for Development / KickOff *(PL -> MA)*
* [x] Umsetzung begonnen *(MA)*
* [x] Umsetzung abgeschlossen *(MA)*
* [x] Sprint Review Meeting (Nachbesprechung) *(PL)*
* [x] Freigabe durch ProductOwner *(PL)*
* [ ] Fakturiert *(PL)*
* [ ] Rebriefing *(PL)*

**Comment by LBeckX** [comment]
@vm1601com klingt nach einer coolen Sache.
Wie würdest Du das implementieren?

**Comment by vm1601com** [comment]
@LBeckX entweder mit einer Checkbox für das dark Theme durch welche dann im Template eine entsprechende Klasse gesetzt wird. Und über diese Klasse kann ich dann die unterschiedlichen Icons ausgeben lassen.
Oder als alternative könnte ich auch durch die Auswahl der checkbox zwei unterschiedliche css Dateien laden lassen.

Die schönste Variante wäre meiner Meinung nach über ein select menü, welches dann eventuell sogar noch erweitert werden kann aber darin sehe ich noch eine etwas höheren Aufwand wie über eine checkbox.

**Comment by LBeckX** [comment]
@vm1601com okay. Um wieviel würde sich der Aufwand erhöhen mit einem Select-Menü?

**Comment by vm1601com** [comment]
@LBeckX wenn das select menü nur in den dca’s erweiterbar ist, sollte das kein so großer Mehraufwand sein. Würde hier mit einer Stunde mehr rechnen also 4h.

**Comment by vm1601com** [comment]
Habe im Backend den Themeswitcher implementiert und das dark Theme ergänzt. d4f24feda272effb507d64de3378b5a880be6371

@LBeckX @FlorianScheyer mit wem kann ich vor der Erstellung einer neuen Version und der Veröffentlichung noch ein Code Review / Nachbesprechung machen?

**Comment by vm1601com** [comment]
Code Review mit FS durchgeführt.

Neuer Release erstellt und diesen auch bei Packagist veröffentlicht.
